### ISSUE TITLE
Incorrect Status

### ISSUE THREAD

**Issue by jadenPete** [whs-computerclub/scheduler#3]
![screenshot 2017-10-10 at 2 27 37 pm](https://user-images.githubusercontent.com/13180372/31411694-3b72114c-adc7-11e7-8ff7-daf8298d2507.png)

**Comment by joshuaSmith2021** [comment]
*should be fixed* -- I will check tomorrow

**Comment by joshuaSmith2021** [comment]
I am now closing the issue -- it is fixed
